[package]
name = "aoc2025_day10"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc2025_utils = { path = "../utils" }
itertools = "0.14.0"
num = "0.4.0"
rustc-hash = "2.1.1"
bitvec = "1.0.1"
regex = "1"

[[bin]]
name = "day10"
path = "main.rs"
