[package]
name = "aoc2025_day10"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc2025_utils = { path = "../utils" }
itertools = "0.14.0"
bitvec = "1.0.1"
regex = "1"
good_lp = { version = "1.14.2", features = ["microlp"] }

[[bin]]
name = "day10"
path = "main.rs"
